package br.com.yomigae.cloudstash.core.model;

public enum Attribute {
    LIFE,
    LIFE_REGENERATION,
    MANA,
    MANA_REGENERATION,
    DEFENSE,
    ATTACK_RATING,
    STRENGTH,
    DEXTERITY,
    VITALITY,
    ENERGY,
    MIN_DAMAGE,
    MAX_DAMAGE,
    FIRE_RESISTANCE,
    COLD_RESISTANCE,
    LIGHTNING_RESISTANCE,
    POISON_RESISTANCE,
    MAGIC_RESISTANCE,
    PHYSICAL_RESISTANCE,
    EXPERIENCE,
    EXPERIENCE_NEXT_LEVEL,
    GOLD
}
