package br.com.yomigae.cloudstash.core;

import br.com.yomigae.cloudstash.core.model.*;
import br.com.yomigae.cloudstash.core.model.character.Character;
import br.com.yomigae.cloudstash.core.model.character.CharacterClass;
import br.com.yomigae.cloudstash.core.model.hireling.Hireling;
import br.com.yomigae.cloudstash.core.model.hireling.HirelingType;
import br.com.yomigae.cloudstash.core.model.progression.*;
import br.com.yomigae.cloudstash.core.parser.DelegatingCharacterParser;

import java.util.List;
import java.util.Map;

import static br.com.yomigae.cloudstash.core.model.Area.*;
import static br.com.yomigae.cloudstash.core.model.Difficulty.*;
import static br.com.yomigae.cloudstash.core.model.progression.Quest.*;
import static java.util.Objects.requireNonNull;

public class D2CloudStash {
    public static void main(String[] args) throws Exception {
        var p = new DelegatingCharacterParser();
        Character c = p.parse(requireNonNull(D2CloudStash.class.getResourceAsStream("/samples/Starfire-6.d2s")));
        System.out.println(c);

        Character.builder()
                .activeEquipmentSet(EquipmentSet.MAIN)
                .ladder(false)
                .expansion(true)
                .dead(false)
                .hardcore(false)
                .currentAct(Act.ACT4_NIGHTMARE)
                .klass(CharacterClass.SORCERESS)
                .level(71)
                .skillHotkeys(List.of(
                        Skill.fromName("Frozen Orb"),
                        Skill.fromName("Hydra"),
                        Skill.fromName("Static Field"),
                        Skill.fromName("Teleport"),
                        Skill.fromName("Tome of Town Portal"),
                        Skill.fromName("Frozen Armor"),
                        Skill.fromName("Telekinesis")))
                .mouseSkill(new Swap<>(
                        new Dual<>(Skill.fromName("Throw"), Skill.fromName("Frozen Orb")),
                        new Dual<>(Skill.fromName("Throw"), Skill.fromName("Frozen Orb"))))
                .name("Starfire")
                .hireling(Hireling.builder()
                        .type(HirelingType.fromId(10, true))
                        .nameId(13)
                        .dead(false)
                        .experience(43555412)
                        .build())
                .progression(new DifficultyMap<>(Map.of(
                        NORMAL, Character.Progression.builder()
                                .act1(Act1Progression.builder()
                                        .difficulty(NORMAL)
                                        .visited(true)
                                        .introduced(true)
                                        .quests()
                                        .set(new QuestStatus.Generic(Quest.DEN_OF_EVIL, true))
                                        .set(new QuestStatus.Generic(SISTERS_BURIAL_GROUNDS, true))
                                        .set(new QuestStatus.Generic(TOOLS_OF_THE_TRADE, true))
                                        .set(new QuestStatus.Generic(THE_SEARCH_FOR_CAIN, true))
                                        .set(new QuestStatus.Generic(THE_FORGOTTEN_TOWER, true))
                                        .set(new QuestStatus.Generic(SISTERS_TO_THE_SLAUGHTER, true))
                                        .done()
                                        .waypoints()
                                        .set(new WaypointStatus(ROGUE_ENCAMPMENT, true))
                                        .set(new WaypointStatus(COLD_PLAINS, true))
                                        .set(new WaypointStatus(STONY_FIELD, true))
                                        .set(new WaypointStatus(DARK_WOOD, true))
                                        .set(new WaypointStatus(BLACK_MARSH, true))
                                        .set(new WaypointStatus(OUTER_CLOISTER, true))
                                        .set(new WaypointStatus(JAIL_LEVEL_1, true))
                                        .set(new WaypointStatus(INNER_CLOISTER, true))
                                        .set(new WaypointStatus(CATACOMBS_LEVEL_2, true))
                                        .done()
                                        .build())
                                .act2(Act2Progression.builder()
                                        .difficulty(NORMAL)
                                        .visited(true)
                                        .introduced(true)
                                        .quests()
                                        .set(new QuestStatus.Generic(RADAMENTS_LAIR, true))
                                        .set(new QuestStatus.Generic(THE_HORADRIC_STAFF, true))
                                        .set(new QuestStatus.Generic(TAINTED_SUN, true))
                                        .set(new QuestStatus.Generic(Quest.ARCANE_SANCTUARY, true))
                                        .set(new QuestStatus.Generic(THE_SUMMONER, true))
                                        .set(new QuestStatus.Generic(THE_SEVEN_TOMBS, true))
                                        .done()
                                        .waypoints()
                                        .set(new WaypointStatus(LUT_GHOLEIN, true))
                                        .set(new WaypointStatus(LUT_GHOLEIN_SEWERS_LEVEL_2, true))
                                        .set(new WaypointStatus(DRY_HILLS, true))
                                        .set(new WaypointStatus(HALLS_OF_THE_DEAD_LEVEL_2, true))
                                        .set(new WaypointStatus(FAR_OASIS, true))
                                        .set(new WaypointStatus(LOST_CITY, true))
                                        .set(new WaypointStatus(PALACE_CELLAR_LEVEL_1, true))
                                        .set(new WaypointStatus(Area.ARCANE_SANCTUARY, true))
                                        .set(new WaypointStatus(CANYON_OF_THE_MAGI, true))
                                        .done()
                                        .build())
                                .act3(Act3Progression.builder()
                                        .difficulty(NORMAL)
                                        .visited(true)
                                        .introduced(true)
                                        .quests()
                                        .set(new QuestStatus.Generic(LAM_ESENS_TOME, true))
                                        .set(new QuestStatus.Generic(KHALIMS_WILL, true))
                                        .set(new QuestStatus.Generic(BLADE_OF_THE_OLD_RELIGION, true))
                                        .set(new QuestStatus.Generic(THE_GOLDEN_BIRD, true))
                                        .set(new QuestStatus.Generic(THE_BLACKENED_TEMPLE, true))
                                        .set(new QuestStatus.Generic(THE_GUARDIAN, true))
                                        .done()
                                        .waypoints()
                                        .set(new WaypointStatus(KURAST_DOCKS, true))
                                        .set(new WaypointStatus(SPIDER_FOREST, true))
                                        .set(new WaypointStatus(GREAT_MARSH, true))
                                        .set(new WaypointStatus(FLAYER_JUNGLE, true))
                                        .set(new WaypointStatus(LOWER_KURAST, true))
                                        .set(new WaypointStatus(KURAST_BAZAAR, true))
                                        .set(new WaypointStatus(UPPER_KURAST, true))
                                        .set(new WaypointStatus(TRAVINCAL, true))
                                        .set(new WaypointStatus(DURANCE_OF_HATE_LEVEL_2, true))
                                        .done()
                                        .build())
                                .act4(Act4Progression.builder()
                                        .difficulty(NORMAL)
                                        .visited(true)
                                        .introduced(true)
                                        .quests()
                                        .set(new QuestStatus.Generic(THE_FALLEN_ANGEL, true))
                                        .set(new QuestStatus.Generic(HELLS_FORGE, true))
                                        .set(new QuestStatus.Generic(TERRORS_END, true))
                                        .done()
                                        .waypoints()
                                        .set(new WaypointStatus(THE_PANDEMONIUM_FORTRESS, true))
                                        .set(new WaypointStatus(CITY_OF_THE_DAMNED, true))
                                        .set(new WaypointStatus(RIVER_OF_FLAME, true))
                                        .done()
                                        .build())
                                .act5(Act5Progression.builder()
                                        .difficulty(NORMAL)
                                        .visited(true)
                                        .introduced(true)
                                        .quests()
                                        .set(new QuestStatus.Generic(SIEGE_ON_HARROGATH, false))
                                        .set(new QuestStatus.Generic(RESCUE_ON_MOUNTAIN_ARREAT, true))
                                        .set(QuestStatus.PrisonOfIce.builder()
                                                .completed(true)
                                                .scrollConsumed(true)
                                                .build())
                                        .set(new QuestStatus.Generic(BETRAYAL_OF_HARROGATH, true))
                                        .set(new QuestStatus.Generic(RITE_OF_PASSAGE, true))
                                        .set(new QuestStatus.Generic(EVE_OF_DESTRUCTION, true))
                                        .done()
                                        .waypoints()
                                        .set(new WaypointStatus(HARROGATH, true))
                                        .set(new WaypointStatus(FRIGID_HIGHLANDS, true))
                                        .set(new WaypointStatus(ARREAT_PLATEAU, true))
                                        .set(new WaypointStatus(CRYSTALLINE_PASSAGE, true))
                                        .set(new WaypointStatus(HALLS_OF_PAIN, true))
                                        .set(new WaypointStatus(GLACIAL_TRAIL, true))
                                        .set(new WaypointStatus(FROZEN_TUNDRA, true))
                                        .set(new WaypointStatus(THE_ANCIENTS_WAY, true))
                                        .set(new WaypointStatus(WORLDSTONE_KEEP_LEVEL_2, true))
                                        .done()
                                        .build())
                                .build(),
                        NIGHTMARE, Character.Progression.builder()
                                .act1(Act1Progression.builder()
                                        .difficulty(NIGHTMARE)
                                        .visited(true)
                                        .introduced(true)
                                        .quests()
                                        .set(new QuestStatus.Generic(Quest.DEN_OF_EVIL, true))
                                        .set(new QuestStatus.Generic(SISTERS_BURIAL_GROUNDS, true))
                                        .set(new QuestStatus.Generic(TOOLS_OF_THE_TRADE, true))
                                        .set(new QuestStatus.Generic(THE_SEARCH_FOR_CAIN, true))
                                        .set(new QuestStatus.Generic(THE_FORGOTTEN_TOWER, true))
                                        .set(new QuestStatus.Generic(SISTERS_TO_THE_SLAUGHTER, true))
                                        .done()
                                        .waypoints()
                                        .set(new WaypointStatus(ROGUE_ENCAMPMENT, true))
                                        .set(new WaypointStatus(COLD_PLAINS, true))
                                        .set(new WaypointStatus(STONY_FIELD, true))
                                        .set(new WaypointStatus(DARK_WOOD, true))
                                        .set(new WaypointStatus(BLACK_MARSH, true))
                                        .set(new WaypointStatus(OUTER_CLOISTER, true))
                                        .set(new WaypointStatus(JAIL_LEVEL_1, true))
                                        .set(new WaypointStatus(INNER_CLOISTER, true))
                                        .set(new WaypointStatus(CATACOMBS_LEVEL_2, true))
                                        .done()
                                        .build())
                                .act2(Act2Progression.builder()
                                        .difficulty(NIGHTMARE)
                                        .visited(true)
                                        .introduced(true)
                                        .quests()
                                        .set(new QuestStatus.Generic(RADAMENTS_LAIR, true))
                                        .set(new QuestStatus.Generic(THE_HORADRIC_STAFF, true))
                                        .set(new QuestStatus.Generic(TAINTED_SUN, true))
                                        .set(new QuestStatus.Generic(Quest.ARCANE_SANCTUARY, true))
                                        .set(new QuestStatus.Generic(THE_SUMMONER, true))
                                        .set(new QuestStatus.Generic(THE_SEVEN_TOMBS, true))
                                        .done()
                                        .waypoints()
                                        .set(new WaypointStatus(LUT_GHOLEIN, true))
                                        .set(new WaypointStatus(LUT_GHOLEIN_SEWERS_LEVEL_2, true))
                                        .set(new WaypointStatus(DRY_HILLS, true))
                                        .set(new WaypointStatus(HALLS_OF_THE_DEAD_LEVEL_2, true))
                                        .set(new WaypointStatus(FAR_OASIS, true))
                                        .set(new WaypointStatus(LOST_CITY, true))
                                        .set(new WaypointStatus(PALACE_CELLAR_LEVEL_1, true))
                                        .set(new WaypointStatus(Area.ARCANE_SANCTUARY, true))
                                        .set(new WaypointStatus(CANYON_OF_THE_MAGI, true))
                                        .done()
                                        .build())
                                .act3(Act3Progression.builder()
                                        .difficulty(NIGHTMARE)
                                        .visited(true)
                                        .introduced(true)
                                        .quests()
                                        .set(new QuestStatus.Generic(LAM_ESENS_TOME, true))
                                        .set(new QuestStatus.Generic(KHALIMS_WILL, true))
                                        .set(new QuestStatus.Generic(BLADE_OF_THE_OLD_RELIGION, true))
                                        .set(new QuestStatus.Generic(THE_GOLDEN_BIRD, true))
                                        .set(new QuestStatus.Generic(THE_BLACKENED_TEMPLE, true))
                                        .set(new QuestStatus.Generic(THE_GUARDIAN, true))
                                        .done()
                                        .waypoints()
                                        .set(new WaypointStatus(KURAST_DOCKS, true))
                                        .set(new WaypointStatus(SPIDER_FOREST, true))
                                        .set(new WaypointStatus(GREAT_MARSH, true))
                                        .set(new WaypointStatus(FLAYER_JUNGLE, true))
                                        .set(new WaypointStatus(LOWER_KURAST, true))
                                        .set(new WaypointStatus(KURAST_BAZAAR, true))
                                        .set(new WaypointStatus(UPPER_KURAST, true))
                                        .set(new WaypointStatus(TRAVINCAL, true))
                                        .set(new WaypointStatus(DURANCE_OF_HATE_LEVEL_2, true))
                                        .done()
                                        .build())
                                .act4(Act4Progression.builder()
                                        .difficulty(NIGHTMARE)
                                        .visited(true)
                                        .introduced(true)
                                        .quests()
                                        .set(new QuestStatus.Generic(THE_FALLEN_ANGEL, true))
                                        .set(new QuestStatus.Generic(HELLS_FORGE, true))
                                        .set(new QuestStatus.Generic(TERRORS_END, true))
                                        .done()
                                        .waypoints()
                                        .set(new WaypointStatus(THE_PANDEMONIUM_FORTRESS, true))
                                        .set(new WaypointStatus(CITY_OF_THE_DAMNED, true))
                                        .set(new WaypointStatus(RIVER_OF_FLAME, true))
                                        .done()
                                        .build())
                                .act5(Act5Progression.builder()
                                        .difficulty(NIGHTMARE)
                                        .visited(true)
                                        .introduced(true)
                                        .quests()
                                        .set(new QuestStatus.Generic(SIEGE_ON_HARROGATH, false))
                                        .set(new QuestStatus.Generic(RESCUE_ON_MOUNTAIN_ARREAT, true))
                                        .set(QuestStatus.PrisonOfIce.builder()
                                                .completed(true)
                                                .scrollConsumed(true)
                                                .build())
                                        .set(new QuestStatus.Generic(BETRAYAL_OF_HARROGATH, true))
                                        .set(new QuestStatus.Generic(RITE_OF_PASSAGE, true))
                                        .set(new QuestStatus.Generic(EVE_OF_DESTRUCTION, true))
                                        .done()
                                        .waypoints()
                                        .set(new WaypointStatus(HARROGATH, true))
                                        .set(new WaypointStatus(FRIGID_HIGHLANDS, true))
                                        .set(new WaypointStatus(ARREAT_PLATEAU, true))
                                        .set(new WaypointStatus(CRYSTALLINE_PASSAGE, true))
                                        .set(new WaypointStatus(HALLS_OF_PAIN, true))
                                        .set(new WaypointStatus(GLACIAL_TRAIL, true))
                                        .set(new WaypointStatus(FROZEN_TUNDRA, true))
                                        .set(new WaypointStatus(THE_ANCIENTS_WAY, true))
                                        .set(new WaypointStatus(WORLDSTONE_KEEP_LEVEL_2, true))
                                        .done()
                                        .build())
                                .build(),
                        HELL, Character.Progression.builder()
                                .act1(Act1Progression.builder()
                                        .difficulty(HELL)
                                        .visited(true)
                                        .introduced(true)
                                        .quests()
                                        .set(new QuestStatus.Generic(Quest.DEN_OF_EVIL, true))
                                        .set(new QuestStatus.Generic(SISTERS_BURIAL_GROUNDS, true))
                                        .set(new QuestStatus.Generic(TOOLS_OF_THE_TRADE, true))
                                        .set(new QuestStatus.Generic(THE_SEARCH_FOR_CAIN, true))
                                        .set(new QuestStatus.Generic(THE_FORGOTTEN_TOWER, true))
                                        .set(new QuestStatus.Generic(SISTERS_TO_THE_SLAUGHTER, true))
                                        .done()
                                        .waypoints()
                                        .set(new WaypointStatus(ROGUE_ENCAMPMENT, true))
                                        .set(new WaypointStatus(COLD_PLAINS, true))
                                        .set(new WaypointStatus(STONY_FIELD, true))
                                        .set(new WaypointStatus(DARK_WOOD, true))
                                        .set(new WaypointStatus(BLACK_MARSH, true))
                                        .set(new WaypointStatus(OUTER_CLOISTER, true))
                                        .set(new WaypointStatus(JAIL_LEVEL_1, true))
                                        .set(new WaypointStatus(INNER_CLOISTER, true))
                                        .set(new WaypointStatus(CATACOMBS_LEVEL_2, true))
                                        .done()
                                        .build())
                                .act2(Act2Progression.builder()
                                        .difficulty(HELL)
                                        .visited(true)
                                        .introduced(true)
                                        .quests()
                                        .set(new QuestStatus.Generic(RADAMENTS_LAIR, true))
                                        .set(new QuestStatus.Generic(THE_HORADRIC_STAFF, true))
                                        .set(new QuestStatus.Generic(TAINTED_SUN, true))
                                        .set(new QuestStatus.Generic(Quest.ARCANE_SANCTUARY, true))
                                        .set(new QuestStatus.Generic(THE_SUMMONER, true))
                                        .set(new QuestStatus.Generic(THE_SEVEN_TOMBS, true))
                                        .done()
                                        .waypoints()
                                        .set(new WaypointStatus(LUT_GHOLEIN, true))
                                        .set(new WaypointStatus(LUT_GHOLEIN_SEWERS_LEVEL_2, true))
                                        .set(new WaypointStatus(DRY_HILLS, true))
                                        .set(new WaypointStatus(HALLS_OF_THE_DEAD_LEVEL_2, true))
                                        .set(new WaypointStatus(FAR_OASIS, true))
                                        .set(new WaypointStatus(LOST_CITY, true))
                                        .set(new WaypointStatus(PALACE_CELLAR_LEVEL_1, true))
                                        .set(new WaypointStatus(Area.ARCANE_SANCTUARY, true))
                                        .set(new WaypointStatus(CANYON_OF_THE_MAGI, true))
                                        .done()
                                        .build())
                                .act3(Act3Progression.builder()
                                        .difficulty(HELL)
                                        .visited(true)
                                        .introduced(true)
                                        .quests()
                                        .set(new QuestStatus.Generic(LAM_ESENS_TOME, true))
                                        .set(new QuestStatus.Generic(KHALIMS_WILL, true))
                                        .set(new QuestStatus.Generic(BLADE_OF_THE_OLD_RELIGION, true))
                                        .set(new QuestStatus.Generic(THE_GOLDEN_BIRD, true))
                                        .set(new QuestStatus.Generic(THE_BLACKENED_TEMPLE, true))
                                        .set(new QuestStatus.Generic(THE_GUARDIAN, true))
                                        .done()
                                        .waypoints()
                                        .set(new WaypointStatus(KURAST_DOCKS, true))
                                        .set(new WaypointStatus(SPIDER_FOREST, true))
                                        .set(new WaypointStatus(GREAT_MARSH, true))
                                        .set(new WaypointStatus(FLAYER_JUNGLE, true))
                                        .set(new WaypointStatus(LOWER_KURAST, true))
                                        .set(new WaypointStatus(KURAST_BAZAAR, true))
                                        .set(new WaypointStatus(UPPER_KURAST, true))
                                        .set(new WaypointStatus(TRAVINCAL, true))
                                        .set(new WaypointStatus(DURANCE_OF_HATE_LEVEL_2, true))
                                        .done()
                                        .build())
                                .act4(Act4Progression.builder()
                                        .difficulty(HELL)
                                        .visited(true)
                                        .introduced(true)
                                        .quests()
                                        .set(new QuestStatus.Generic(THE_FALLEN_ANGEL, true))
                                        .set(new QuestStatus.Generic(HELLS_FORGE, true))
                                        .set(new QuestStatus.Generic(TERRORS_END, true))
                                        .done()
                                        .waypoints()
                                        .set(new WaypointStatus(THE_PANDEMONIUM_FORTRESS, true))
                                        .set(new WaypointStatus(CITY_OF_THE_DAMNED, true))
                                        .set(new WaypointStatus(RIVER_OF_FLAME, true))
                                        .done()
                                        .build())
                                .act5(Act5Progression.builder()
                                        .difficulty(HELL)
                                        .visited(true)
                                        .introduced(true)
                                        .quests()
                                        .set(new QuestStatus.Generic(SIEGE_ON_HARROGATH, false))
                                        .set(new QuestStatus.Generic(RESCUE_ON_MOUNTAIN_ARREAT, true))
                                        .set(QuestStatus.PrisonOfIce.builder()
                                                .completed(true)
                                                .scrollConsumed(true)
                                                .build())
                                        .set(new QuestStatus.Generic(BETRAYAL_OF_HARROGATH, true))
                                        .set(new QuestStatus.Generic(RITE_OF_PASSAGE, true))
                                        .set(new QuestStatus.Generic(EVE_OF_DESTRUCTION, true))
                                        .done()
                                        .waypoints()
                                        .set(new WaypointStatus(HARROGATH, true))
                                        .set(new WaypointStatus(FRIGID_HIGHLANDS, true))
                                        .set(new WaypointStatus(ARREAT_PLATEAU, true))
                                        .set(new WaypointStatus(CRYSTALLINE_PASSAGE, true))
                                        .set(new WaypointStatus(HALLS_OF_PAIN, true))
                                        .set(new WaypointStatus(GLACIAL_TRAIL, true))
                                        .set(new WaypointStatus(FROZEN_TUNDRA, true))
                                        .set(new WaypointStatus(THE_ANCIENTS_WAY, true))
                                        .set(new WaypointStatus(WORLDSTONE_KEEP_LEVEL_2, true))
                                        .done()
                                        .build())
                                .build()
                )))
                .build();
    }
}
