package br.com.yomigae.cloudstash.core;

import br.com.yomigae.cloudstash.core.model.character.Character;
import br.com.yomigae.cloudstash.core.parser.DelegatingCharacterParser;

import static java.util.Objects.requireNonNull;

public class D2CloudStash {
    public static void main(String[] args) throws Exception {
        var p = new DelegatingCharacterParser();
        Character c = p.parse(requireNonNull(D2CloudStash.class.getResourceAsStream("/samples/Starfire-6.d2s")));
        System.out.println(c);
//
//        Character.builder()
//                .activeEquipmentSet(EquipmentSet.MAIN)
//                .ladder(false)
//                .expansion(true)
//                .dead(false)
//                .hardcore(false)
//                .currentAct(Act.ACT4_NIGHTMARE)
//                .clazz(CharacterClass.SORCERESS)
//                .level(71)
//                .skillHotkeys(List.of(
//                        Skill.fromName("Frozen Orb"),
//                        Skill.fromName("Hydra"),
//                        Skill.fromName("Static Field"),
//                        Skill.fromName("Teleport"),
//                        Skill.fromName("Tome of Town Portal"),
//                        Skill.fromName("Frozen Armor"),
//                        Skill.fromName("Telekinesis")))
//                .mouseSkill(new Swap<>(
//                        new Dual<>(Skill.fromName("Throw"), Skill.fromName("Frozen Orb")),
//                        new Dual<>(Skill.fromName("Throw"), Skill.fromName("Frozen Orb"))))
//                .name("Starfire")
//                .hireling(Hireling.builder()
//                        .clazz(HirelingType.fromId(10, true))
//                        .nameId(13)
//                        .dead(false)
//                        .experience(43555412)
//                        .build())
//                .acts(NORMAL, Character.Acts.blau()
//                                .act1(ActStatus.Act1.builder()
//                                        .difficulty(NORMAL)
//                                        .visited(true)
//                                        .introduced(true)
//                                        .quests(ActStatus.Act1.Quests.builder()
//                                                .denOfEvil(new Generic(true))
//                                                .sistersBurialGrounds(new Generic(true))
//                                                .toolsOfTheTrade(new Generic(true))
//                                                .theSearchForCain(new Generic(true))
//                                                .theForgottenTower(new Generic(true))
//                                                .sistersToTheSlaughter(new Generic(true))
//                                                .build())
//                                        .waypoints(ActStatus.Act1.Waypoints.builder()
//                                                .rogueEncampment(true)
//                                                .coldPlains(true)
//                                                .stonyField(true)
//                                                .darkWood(true)
//                                                .blackMarsh(true)
//                                                .outerCloister(true)
//                                                .jail(true)
//                                                .innerCloister(true)
//                                                .catacombs(true)
//                                                .build())
//                                        .build())
//                                .act2(ActStatus.Act2.builder()
//                                        .difficulty(NORMAL)
//                                        .visited(true)
//                                        .introduced(true)
//                                        .quests()
//                                        .radamentsLair(new Generic(true))
//                                        .theHoradricStaff(new Generic(true))
//                                        .taintedSun(new Generic(true))
//                                        .arcaneSanctuary(new Generic(true))
//                                        .theSummoner(new Generic(true))
//                                        .theSevenTombs(new Generic(true))
//                                        .done()
//                                        .waypoints()
//                                        .lutGholein(true)
//                                        .lutGholeinSewers(true)
//                                        .dryHills(true)
//                                        .hallsOfTheDead(true)
//                                        .farOasis(true)
//                                        .lostCity(true)
//                                        .palaceCellar(true)
//                                        .arcaneSanctuary(true)
//                                        .canyonOfTheMagi(true)
//                                        .done()
//                                        .build())
//                                .act3(ActStatus.Act3.builder()
//                                        .difficulty(NORMAL)
//                                        .visited(true)
//                                        .introduced(true)
//                                        .quests()
//                                        .lamEsensTome(new Generic(true))
//                                        .khalimsWill(new Generic(true))
//                                        .bladeOfTheOldReligion(new Generic(true))
//                                        .theGoldenBird(new Generic(true))
//                                        .theBlackenedTemple(new Generic(true))
//                                        .theGuardian(new Generic(true))
//                                        .done()
//                                        .waypoints()
//                                        .kurastDocks(true)
//                                        .spiderForest(true)
//                                        .greatMarsh(true)
//                                        .flayerJungle(true)
//                                        .lowerKurast(true)
//                                        .kurastBazaar(true)
//                                        .upperKurast(true)
//                                        .travincal(true)
//                                        .duranceOfHate(true)
//                                        .done()
//                                        .build())
//                                .act4(ActStatus.Act4.builder()
//                                        .difficulty(NORMAL)
//                                        .visited(true)
//                                        .introduced(true)
//                                        .quests()
//                                        .theFallenAngel(new Generic(true))
//                                        .hellsForge(new Generic(true))
//                                        .terrorsEnd(new Generic(true))
//                                        .done()
//                                        .waypoints()
//                                        .thePandemoniumFortress(true)
//                                        .cityOfTheDamned(true)
//                                        .riverOfFlame(true)
//                                        .done()
//                                        .build())
//                                .act5(ActStatus.Act5.builder()
//                                        .difficulty(NORMAL)
//                                        .visited(true)
//                                        .introduced(true)
//                                        .quests()
//                                        .siegeOnHarrogath(new Generic(false))
//                                        .rescueOnMountainArreat(new Generic(true))
//                                        .set(QuestStatus.PrisonOfIce.builder()
//                                                .completed(true)
//                                                .scrollConsumed(true)
//                                                .build())
//                                        .betrayalOfHarrogath(new Generic(true))
//                                        .riteOfPassage(new Generic(true))
//                                        .eveOfDestruction(new Generic(true))
//                                        .done()
//                                        .waypoints()
//                                        .harrogath(true)
//                                        .frigidHighlands(true)
//                                        .arreatPlateau(true)
//                                        .crystallinePassage(true)
//                                        .hallsOfPain(true)
//                                        .glacialTrail(true)
//                                        .frozenTundra(true)
//                                        .theAncientsWay(true)
//                                        .worldstoneKeep(true)
//                                        .done()
//                                        .build())
//                                .build(),
//                        NIGHTMARE, Character.Acts.builder()
//                                .act1(ActStatus.Act1.builder()
//                                        .difficulty(NIGHTMARE)
//                                        .visited(true)
//                                        .introduced(true)
//                                        .quests()
//                                        .denOfEvil(new Generic(true))
//                                        .sistersBurialGrounds(new Generic(true))
//                                        .toolsOfTheTrade(new Generic(true))
//                                        .theSearchForCain(new Generic(true))
//                                        .theForgottenTower(new Generic(true))
//                                        .sistersToTheSlaughter(new Generic(true))
//                                        .done()
//                                        .waypoints()
//                                        .rogueEncampment(true))
//                                .coldPlains(true)
//                                .stonyField(true)
//                                .darkWood(true)
//                                .blackMarsh(true)
//                                .outerCloister(true)
//                                .jail(true)
//                                .innerCloister(true)
//                                .catacombs(true)
//                                .done()
//                                .build())
//                .act2(ActStatus.Act2.builder()
//                        .difficulty(NIGHTMARE)
//                        .visited(true)
//                        .introduced(true)
//                        .quests()
//                        .radamentsLair(new Generic(true))
//                        .theHoradricStaff(new Generic(true))
//                        .taintedSun(new Generic(true))
//                        .arcaneSanctuary(new Generic(true))
//                        .theSummoner(new Generic(true))
//                        .theSevenTombs(new Generic(true))
//                        .done()
//                        .waypoints()
//                        .lutGholein(true)
//                        .lutGholeinSewers(true)
//                        .dryHills(true)
//                        .hallsOfTheDead(true)
//                        .farOasis(true)
//                        .lostCity(true)
//                        .palaceCellar(true)
//                        .arcaneSanctuary(true)
//                        .canyonOfTheMagi(true)
//                        .done()
//                        .build())
//                .act3(ActStatus.Act3.builder()
//                        .difficulty(NIGHTMARE)
//                        .visited(true)
//                        .introduced(true)
//                        .quests()
//                        .lamEsensTome(new Generic(true))
//                        .khalimsWill(new Generic(true))
//                        .bladeOfTheOldReligion(new Generic(true))
//                        .theGoldenBird(new Generic(true))
//                        .theBlackenedTemple(new Generic(true))
//                        .theGuardian(new Generic(true))
//                        .done()
//                        .waypoints()
//                        .kurastDocks(true)
//                        .spiderForest(true)
//                        .greatMarsh(true)
//                        .flayerJungle(true)
//                        .lowerKurast(true)
//                        .kurastBazaar(true)
//                        .upperKurast(true)
//                        .travincal(true)
//                        .duranceOfHate(true)
//                        .done()
//                        .build())
//                .act4(ActStatus.Act4.builder()
//                        .difficulty(NIGHTMARE)
//                        .visited(true)
//                        .introduced(true)
//                        .quests()
//                        .theFallenAngel(new Generic(true))
//                        .hellsForge(new Generic(true))
//                        .terrorsEnd(new Generic(true))
//                        .done()
//                        .waypoints()
//                        .thePandemoniumFortress(true)
//                        .cityOfTheDamned(true)
//                        .riverOfFlame(true)
//                        .done()
//                        .build())
//                .act5(ActStatus.Act5.builder()
//                        .difficulty(NIGHTMARE)
//                        .visited(true)
//                        .introduced(true)
//                        .quests()
//                        .siegeOnHarrogath(new Generic(false))
//                        .rescueOnMountainArreat(new Generic(true))
//                        .set(QuestStatus.PrisonOfIce.builder()
//                                .completed(true)
//                                .scrollConsumed(true)
//                                .build())
//                        .betrayalOfHarrogath(new Generic(true))
//                        .riteOfPassage(new Generic(true))
//                        .eveOfDestruction(new Generic(true))
//                        .done()
//                        .waypoints()
//                        .harrogath(true)
//                        .frigidHighlands(true)
//                        .arreatPlateau(true)
//                        .crystallinePassage(true)
//                        .hallsOfPain(true)
//                        .glacialTrail(true)
//                        .frozenTundra(true)
//                        .theAncientsWay(true)
//                        .worldstoneKeep(true)
//                        .done()
//                        .build())
//                .build(),
//                HELL, Character.Acts.builder()
//                .act1(ActStatus.Act1.builder()
//                        .difficulty(HELL)
//                        .visited(true)
//                        .introduced(true)
//                        .quests()
//                        .denOfEvil(new Generic(true))
//                        .sistersBurialGrounds(new Generic(true))
//                        .toolsOfTheTrade(new Generic(true))
//                        .theSearchForCain(new Generic(true))
//                        .theForgottenTower(new Generic(true))
//                        .sistersToTheSlaughter(new Generic(true))
//                        .done()
//                        .waypoints()
//                        .rogueEncampment(true))
//                .coldPlains(true)
//                .stonyField(true)
//                .darkWood(true)
//                .blackMarsh(true)
//                .outerCloister(true)
//                .jail(true)
//                .innerCloister(true)
//                .catacombs(true)
//                .done()
//                .build())
//                                .act2(ActStatus.Act2.builder()
//                .difficulty(HELL)
//                .visited(true)
//                .introduced(true)
//                .quests()
//                .radamentsLair(new Generic(true))
//                .theHoradricStaff(new Generic(true))
//                .taintedSun(new Generic(true))
//                .arcaneSanctuary(new Generic(true))
//                .theSummoner(new Generic(true))
//                .theSevenTombs(new Generic(true))
//                .done()
//                .waypoints()
//                .lutGholein(true)
//                .lutGholeinSewers(true)
//                .dryHills(true)
//                .hallsOfTheDead(true)
//                .farOasis(true)
//                .lostCity(true)
//                .palaceCellar(true)
//                .arcaneSanctuary(true)
//                .canyonOfTheMagi(true)
//                .done()
//                .build())
//                .act3(ActStatus.Act3.builder()
//                        .difficulty(HELL)
//                        .visited(true)
//                        .introduced(true)
//                        .quests()
//                        .lamEsensTome(new Generic(true))
//                        .khalimsWill(new Generic(true))
//                        .bladeOfTheOldReligion(new Generic(true))
//                        .theGoldenBird(new Generic(true))
//                        .theBlackenedTemple(new Generic(true))
//                        .theGuardian(new Generic(true))
//                        .done()
//                        .waypoints()
//                        .kurastDocks(true)
//                        .spiderForest(true)
//                        .greatMarsh(true)
//                        .flayerJungle(true)
//                        .lowerKurast(true)
//                        .kurastBazaar(true)
//                        .upperKurast(true)
//                        .travincal(true)
//                        .duranceOfHate(true)
//                        .done()
//                        .build())
//                .act4(ActStatus.Act4.builder()
//                        .difficulty(HELL)
//                        .visited(true)
//                        .introduced(true)
//                        .quests()
//                        .theFallenAngel(new Generic(true))
//                        .hellsForge(new Generic(true))
//                        .terrorsEnd(new Generic(true))
//                        .done()
//                        .waypoints()
//                        .thePandemoniumFortress(true)
//                        .cityOfTheDamned(true)
//                        .riverOfFlame(true)
//                        .done()
//                        .build())
//                .act5(ActStatus.Act5.builder()
//                        .difficulty(HELL)
//                        .visited(true)
//                        .introduced(true)
//                        .quests()
//                        .siegeOnHarrogath(new Generic(false))
//                        .rescueOnMountainArreat(new Generic(true))
//                        .set(QuestStatus.PrisonOfIce.builder()
//                                .completed(true)
//                                .scrollConsumed(true)
//                                .build())
//                        .betrayalOfHarrogath(new Generic(true))
//                        .riteOfPassage(new Generic(true))
//                        .eveOfDestruction(new Generic(true))
//                        .done()
//                        .waypoints()
//                        .harrogath(true)
//                        .frigidHighlands(true)
//                        .arreatPlateau(true)
//                        .crystallinePassage(true)
//                        .hallsOfPain(true)
//                        .glacialTrail(true)
//                        .frozenTundra(true)
//                        .theAncientsWay(true)
//                        .worldstoneKeep(true)
//                        .done()
//                        .build())
//                .build()
//                )))
//                .build();
    }
}
