package br.com.yomigae.cloudstash.core;

import br.com.yomigae.cloudstash.core.model.character.Character;
import br.com.yomigae.cloudstash.core.parser.DelegatingCharacterParser;

import static java.util.Objects.requireNonNull;
import static org.assertj.core.api.Assertions.assertThat;

public class SampleTest {

    private static final DelegatingCharacterParser PARSER = new DelegatingCharacterParser();
//
//    @Test
//    void testStarfire6() {
//        assertCharacter("/samples/Starfire-6.d2s", Character.builder()
//                .name("Starfire")
//                .level(71)
//                .clazz(CharacterClass.SORCERESS)
//                .ladder(false)
//                .expansion(true)
//                .dead(true)
//                .hardcore(false)
//                .currentAct(Act.ACT4_NIGHTMARE)
//                .activeEquipmentSet(EquipmentSet.MAIN)
//                .skillHotkeys(List.of(
//                        Skill.fromName("Frozen Orb"),
//                        Skill.fromName("Hydra"),
//                        Skill.fromName("Static Field"),
//                        Skill.fromName("Teleport"),
//                        Skill.fromName("Tome of Town Portal"),
//                        Skill.fromName("Frozen Armor"),
//                        Skill.fromName("Telekinesis")))
//                .mouseSkill(new Swap<>(
//                        new Dual<>(Skill.fromName("Throw"), Skill.fromName("Frozen Orb")),
//                        new Dual<>(Skill.fromName("Throw"), Skill.fromName("Frozen Orb"))))
//                .hireling(Hireling.builder()
//                        .clazz(HirelingType.fromId(10, true))
//                        .nameId(13)
//                        .dead(false)
//                        .experience(43555412)
//                        .build())
//                .progression(new DifficultyMap<>(Map.of(
//                        NORMAL, Character.Acts.builder()
//                                .act1(Act1Progression.builder()
//                                        .difficulty(NORMAL)
//                                        .visited(true)
//                                        .introduced(true)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.DEN_OF_EVIL, true))
//                                        .set(new QuestStatus.Generic(Quest.SISTERS_BURIAL_GROUNDS, true))
//                                        .set(new QuestStatus.Generic(Quest.TOOLS_OF_THE_TRADE, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_SEARCH_FOR_CAIN, true))
//                                        .set(new QuestStatus.Generic(Quest.THE_FORGOTTEN_TOWER, true))
//                                        .set(new QuestStatus.Generic(Quest.SISTERS_TO_THE_SLAUGHTER, true))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.ROGUE_ENCAMPMENT, true))
//                                        .set(new WaypointStatus(Area.COLD_PLAINS, true))
//                                        .set(new WaypointStatus(Area.STONY_FIELD, true))
//                                        .set(new WaypointStatus(Area.DARK_WOOD, true))
//                                        .set(new WaypointStatus(Area.BLACK_MARSH, true))
//                                        .set(new WaypointStatus(Area.OUTER_CLOISTER, true))
//                                        .set(new WaypointStatus(Area.JAIL_LEVEL_1, true))
//                                        .set(new WaypointStatus(Area.INNER_CLOISTER, true))
//                                        .set(new WaypointStatus(Area.CATACOMBS_LEVEL_2, true))
//                                        .done()
//                                        .build())
//                                .act2(Act2Progression.builder()
//                                        .difficulty(NORMAL)
//                                        .visited(true)
//                                        .introduced(true)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.RADAMENTS_LAIR, true))
//                                        .set(new QuestStatus.Generic(Quest.THE_HORADRIC_STAFF, true))
//                                        .set(new QuestStatus.Generic(Quest.TAINTED_SUN, true))
//                                        .set(new QuestStatus.Generic(Quest.ARCANE_SANCTUARY, true))
//                                        .set(new QuestStatus.Generic(Quest.THE_SUMMONER, true))
//                                        .set(new QuestStatus.Generic(Quest.THE_SEVEN_TOMBS, true))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.LUT_GHOLEIN, true))
//                                        .set(new WaypointStatus(Area.LUT_GHOLEIN_SEWERS_LEVEL_2, true))
//                                        .set(new WaypointStatus(Area.DRY_HILLS, true))
//                                        .set(new WaypointStatus(Area.HALLS_OF_THE_DEAD_LEVEL_2, true))
//                                        .set(new WaypointStatus(Area.FAR_OASIS, true))
//                                        .set(new WaypointStatus(Area.LOST_CITY, true))
//                                        .set(new WaypointStatus(Area.PALACE_CELLAR_LEVEL_1, true))
//                                        .set(new WaypointStatus(Area.ARCANE_SANCTUARY, true))
//                                        .set(new WaypointStatus(Area.CANYON_OF_THE_MAGI, true))
//                                        .done()
//                                        .build())
//                                .act3(Act3Progression.builder()
//                                        .difficulty(NORMAL)
//                                        .visited(true)
//                                        .introduced(true)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.LAM_ESENS_TOME, true))
//                                        .set(new QuestStatus.Generic(Quest.KHALIMS_WILL, true))
//                                        .set(new QuestStatus.Generic(Quest.BLADE_OF_THE_OLD_RELIGION, true))
//                                        .set(new QuestStatus.Generic(Quest.THE_GOLDEN_BIRD, true))
//                                        .set(new QuestStatus.Generic(Quest.THE_BLACKENED_TEMPLE, true))
//                                        .set(new QuestStatus.Generic(Quest.THE_GUARDIAN, true))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.KURAST_DOCKS, true))
//                                        .set(new WaypointStatus(Area.SPIDER_FOREST, true))
//                                        .set(new WaypointStatus(Area.GREAT_MARSH, false))
//                                        .set(new WaypointStatus(Area.FLAYER_JUNGLE, true))
//                                        .set(new WaypointStatus(Area.LOWER_KURAST, true))
//                                        .set(new WaypointStatus(Area.KURAST_BAZAAR, true))
//                                        .set(new WaypointStatus(Area.UPPER_KURAST, false))
//                                        .set(new WaypointStatus(Area.TRAVINCAL, true))
//                                        .set(new WaypointStatus(Area.DURANCE_OF_HATE_LEVEL_2, true))
//                                        .done()
//                                        .build())
//                                .act4(Act4Progression.builder()
//                                        .difficulty(NORMAL)
//                                        .visited(true)
//                                        .introduced(true)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.THE_FALLEN_ANGEL, true))
//                                        .set(new QuestStatus.Generic(Quest.HELLS_FORGE, true))
//                                        .set(new QuestStatus.Generic(Quest.TERRORS_END, true))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.THE_PANDEMONIUM_FORTRESS, true))
//                                        .set(new WaypointStatus(Area.CITY_OF_THE_DAMNED, true))
//                                        .set(new WaypointStatus(Area.RIVER_OF_FLAME, true))
//                                        .done()
//                                        .build())
//                                .act5(Act5Progression.builder()
//                                        .difficulty(NORMAL)
//                                        .visited(true)
//                                        .introduced(true)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.SIEGE_ON_HARROGATH, false))
//                                        .set(new QuestStatus.Generic(Quest.RESCUE_ON_MOUNTAIN_ARREAT, true))
//                                        .set(QuestStatus.PrisonOfIce.builder()
//                                                .completed(true)
//                                                .scrollConsumed(true)
//                                                .build())
//                                        .set(new QuestStatus.Generic(Quest.BETRAYAL_OF_HARROGATH, false))
//                                        .set(new QuestStatus.Generic(Quest.RITE_OF_PASSAGE, true))
//                                        .set(new QuestStatus.Generic(Quest.EVE_OF_DESTRUCTION, true))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.HARROGATH, true))
//                                        .set(new WaypointStatus(Area.FRIGID_HIGHLANDS, true))
//                                        .set(new WaypointStatus(Area.ARREAT_PLATEAU, true))
//                                        .set(new WaypointStatus(Area.CRYSTALLINE_PASSAGE, true))
//                                        .set(new WaypointStatus(Area.HALLS_OF_PAIN, true))
//                                        .set(new WaypointStatus(Area.GLACIAL_TRAIL, true))
//                                        .set(new WaypointStatus(Area.FROZEN_TUNDRA, false))
//                                        .set(new WaypointStatus(Area.THE_ANCIENTS_WAY, true))
//                                        .set(new WaypointStatus(Area.WORLDSTONE_KEEP_LEVEL_2, true))
//                                        .done()
//                                        .build())
//                                .build(),
//                        NIGHTMARE, Character.Acts.builder()
//                                .act1(Act1Progression.builder()
//                                        .difficulty(NIGHTMARE)
//                                        .visited(true)
//                                        .introduced(true)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.DEN_OF_EVIL, true))
//                                        .set(new QuestStatus.Generic(Quest.SISTERS_BURIAL_GROUNDS, true))
//                                        .set(new QuestStatus.Generic(Quest.TOOLS_OF_THE_TRADE, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_SEARCH_FOR_CAIN, true))
//                                        .set(new QuestStatus.Generic(Quest.THE_FORGOTTEN_TOWER, true))
//                                        .set(new QuestStatus.Generic(Quest.SISTERS_TO_THE_SLAUGHTER, true))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.ROGUE_ENCAMPMENT, true))
//                                        .set(new WaypointStatus(Area.COLD_PLAINS, true))
//                                        .set(new WaypointStatus(Area.STONY_FIELD, true))
//                                        .set(new WaypointStatus(Area.DARK_WOOD, true))
//                                        .set(new WaypointStatus(Area.BLACK_MARSH, true))
//                                        .set(new WaypointStatus(Area.OUTER_CLOISTER, true))
//                                        .set(new WaypointStatus(Area.JAIL_LEVEL_1, true))
//                                        .set(new WaypointStatus(Area.INNER_CLOISTER, true))
//                                        .set(new WaypointStatus(Area.CATACOMBS_LEVEL_2, true))
//                                        .done()
//                                        .build())
//                                .act2(Act2Progression.builder()
//                                        .difficulty(NIGHTMARE)
//                                        .visited(true)
//                                        .introduced(true)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.RADAMENTS_LAIR, true))
//                                        .set(new QuestStatus.Generic(Quest.THE_HORADRIC_STAFF, true))
//                                        .set(new QuestStatus.Generic(Quest.TAINTED_SUN, true))
//                                        .set(new QuestStatus.Generic(Quest.ARCANE_SANCTUARY, true))
//                                        .set(new QuestStatus.Generic(Quest.THE_SUMMONER, true))
//                                        .set(new QuestStatus.Generic(Quest.THE_SEVEN_TOMBS, true))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.LUT_GHOLEIN, true))
//                                        .set(new WaypointStatus(Area.LUT_GHOLEIN_SEWERS_LEVEL_2, true))
//                                        .set(new WaypointStatus(Area.DRY_HILLS, true))
//                                        .set(new WaypointStatus(Area.HALLS_OF_THE_DEAD_LEVEL_2, false))
//                                        .set(new WaypointStatus(Area.FAR_OASIS, true))
//                                        .set(new WaypointStatus(Area.LOST_CITY, true))
//                                        .set(new WaypointStatus(Area.PALACE_CELLAR_LEVEL_1, true))
//                                        .set(new WaypointStatus(Area.ARCANE_SANCTUARY, true))
//                                        .set(new WaypointStatus(Area.CANYON_OF_THE_MAGI, true))
//                                        .done()
//                                        .build())
//                                .act3(Act3Progression.builder()
//                                        .difficulty(NIGHTMARE)
//                                        .visited(true)
//                                        .introduced(true)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.LAM_ESENS_TOME, true))
//                                        .set(new QuestStatus.Generic(Quest.KHALIMS_WILL, true))
//                                        .set(new QuestStatus.Generic(Quest.BLADE_OF_THE_OLD_RELIGION, true))
//                                        .set(new QuestStatus.Generic(Quest.THE_GOLDEN_BIRD, true))
//                                        .set(new QuestStatus.Generic(Quest.THE_BLACKENED_TEMPLE, true))
//                                        .set(new QuestStatus.Generic(Quest.THE_GUARDIAN, true))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.KURAST_DOCKS, true))
//                                        .set(new WaypointStatus(Area.SPIDER_FOREST, true))
//                                        .set(new WaypointStatus(Area.GREAT_MARSH, false))
//                                        .set(new WaypointStatus(Area.FLAYER_JUNGLE, false))
//                                        .set(new WaypointStatus(Area.LOWER_KURAST, true))
//                                        .set(new WaypointStatus(Area.KURAST_BAZAAR, true))
//                                        .set(new WaypointStatus(Area.UPPER_KURAST, true))
//                                        .set(new WaypointStatus(Area.TRAVINCAL, true))
//                                        .set(new WaypointStatus(Area.DURANCE_OF_HATE_LEVEL_2, true))
//                                        .done()
//                                        .build())
//                                .act4(Act4Progression.builder()
//                                        .difficulty(NIGHTMARE)
//                                        .visited(true)
//                                        .introduced(true)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.THE_FALLEN_ANGEL, true))
//                                        .set(new QuestStatus.Generic(Quest.HELLS_FORGE, true))
//                                        .set(new QuestStatus.Generic(Quest.TERRORS_END, true))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.THE_PANDEMONIUM_FORTRESS, true))
//                                        .set(new WaypointStatus(Area.CITY_OF_THE_DAMNED, true))
//                                        .set(new WaypointStatus(Area.RIVER_OF_FLAME, true))
//                                        .done()
//                                        .build())
//                                .act5(Act5Progression.builder()
//                                        .difficulty(NIGHTMARE)
//                                        .visited(true)
//                                        .introduced(true)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.SIEGE_ON_HARROGATH, false))
//                                        .set(new QuestStatus.Generic(Quest.RESCUE_ON_MOUNTAIN_ARREAT, true))
//                                        .set(QuestStatus.PrisonOfIce.builder()
//                                                .completed(true)
//                                                .scrollConsumed(true)
//                                                .build())
//                                        .set(new QuestStatus.Generic(Quest.BETRAYAL_OF_HARROGATH, false))
//                                        .set(new QuestStatus.Generic(Quest.RITE_OF_PASSAGE, true))
//                                        .set(new QuestStatus.Generic(Quest.EVE_OF_DESTRUCTION, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.HARROGATH, true))
//                                        .set(new WaypointStatus(Area.FRIGID_HIGHLANDS, true))
//                                        .set(new WaypointStatus(Area.ARREAT_PLATEAU, false))
//                                        .set(new WaypointStatus(Area.CRYSTALLINE_PASSAGE, true))
//                                        .set(new WaypointStatus(Area.HALLS_OF_PAIN, true))
//                                        .set(new WaypointStatus(Area.GLACIAL_TRAIL, false))
//                                        .set(new WaypointStatus(Area.FROZEN_TUNDRA, false))
//                                        .set(new WaypointStatus(Area.THE_ANCIENTS_WAY, true))
//                                        .set(new WaypointStatus(Area.WORLDSTONE_KEEP_LEVEL_2, true))
//                                        .done()
//                                        .build())
//                                .build(),
//                        HELL, Character.Acts.builder()
//                                .act1(Act1Progression.builder()
//                                        .difficulty(HELL)
//                                        .visited(true)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.DEN_OF_EVIL, false))
//                                        .set(new QuestStatus.Generic(Quest.SISTERS_BURIAL_GROUNDS, false))
//                                        .set(new QuestStatus.Generic(Quest.TOOLS_OF_THE_TRADE, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_SEARCH_FOR_CAIN, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_FORGOTTEN_TOWER, false))
//                                        .set(new QuestStatus.Generic(Quest.SISTERS_TO_THE_SLAUGHTER, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.ROGUE_ENCAMPMENT, true))
//                                        .set(new WaypointStatus(Area.COLD_PLAINS, false))
//                                        .set(new WaypointStatus(Area.STONY_FIELD, false))
//                                        .set(new WaypointStatus(Area.DARK_WOOD, false))
//                                        .set(new WaypointStatus(Area.BLACK_MARSH, false))
//                                        .set(new WaypointStatus(Area.OUTER_CLOISTER, false))
//                                        .set(new WaypointStatus(Area.JAIL_LEVEL_1, false))
//                                        .set(new WaypointStatus(Area.INNER_CLOISTER, false))
//                                        .set(new WaypointStatus(Area.CATACOMBS_LEVEL_2, false))
//                                        .done()
//                                        .build())
//                                .act2(Act2Progression.builder()
//                                        .difficulty(HELL)
//                                        .visited(false)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.RADAMENTS_LAIR, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_HORADRIC_STAFF, false))
//                                        .set(new QuestStatus.Generic(Quest.TAINTED_SUN, false))
//                                        .set(new QuestStatus.Generic(Quest.ARCANE_SANCTUARY, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_SUMMONER, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_SEVEN_TOMBS, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.LUT_GHOLEIN, false))
//                                        .set(new WaypointStatus(Area.LUT_GHOLEIN_SEWERS_LEVEL_2, false))
//                                        .set(new WaypointStatus(Area.DRY_HILLS, false))
//                                        .set(new WaypointStatus(Area.HALLS_OF_THE_DEAD_LEVEL_2, false))
//                                        .set(new WaypointStatus(Area.FAR_OASIS, false))
//                                        .set(new WaypointStatus(Area.LOST_CITY, false))
//                                        .set(new WaypointStatus(Area.PALACE_CELLAR_LEVEL_1, false))
//                                        .set(new WaypointStatus(Area.ARCANE_SANCTUARY, false))
//                                        .set(new WaypointStatus(Area.CANYON_OF_THE_MAGI, false))
//                                        .done()
//                                        .build())
//                                .act3(Act3Progression.builder()
//                                        .difficulty(HELL)
//                                        .visited(false)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.LAM_ESENS_TOME, false))
//                                        .set(new QuestStatus.Generic(Quest.KHALIMS_WILL, false))
//                                        .set(new QuestStatus.Generic(Quest.BLADE_OF_THE_OLD_RELIGION, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_GOLDEN_BIRD, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_BLACKENED_TEMPLE, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_GUARDIAN, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.KURAST_DOCKS, false))
//                                        .set(new WaypointStatus(Area.SPIDER_FOREST, false))
//                                        .set(new WaypointStatus(Area.GREAT_MARSH, false))
//                                        .set(new WaypointStatus(Area.FLAYER_JUNGLE, false))
//                                        .set(new WaypointStatus(Area.LOWER_KURAST, false))
//                                        .set(new WaypointStatus(Area.KURAST_BAZAAR, false))
//                                        .set(new WaypointStatus(Area.UPPER_KURAST, false))
//                                        .set(new WaypointStatus(Area.TRAVINCAL, false))
//                                        .set(new WaypointStatus(Area.DURANCE_OF_HATE_LEVEL_2, false))
//                                        .done()
//                                        .build())
//                                .act4(Act4Progression.builder()
//                                        .difficulty(HELL)
//                                        .visited(false)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.THE_FALLEN_ANGEL, false))
//                                        .set(new QuestStatus.Generic(Quest.HELLS_FORGE, false))
//                                        .set(new QuestStatus.Generic(Quest.TERRORS_END, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.THE_PANDEMONIUM_FORTRESS, false))
//                                        .set(new WaypointStatus(Area.CITY_OF_THE_DAMNED, false))
//                                        .set(new WaypointStatus(Area.RIVER_OF_FLAME, false))
//                                        .done()
//                                        .build())
//                                .act5(Act5Progression.builder()
//                                        .difficulty(HELL)
//                                        .visited(false)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.SIEGE_ON_HARROGATH, false))
//                                        .set(new QuestStatus.Generic(Quest.RESCUE_ON_MOUNTAIN_ARREAT, false))
//                                        .set(QuestStatus.PrisonOfIce.builder()
//                                                .completed(false)
//                                                .scrollConsumed(false)
//                                                .build())
//                                        .set(new QuestStatus.Generic(Quest.BETRAYAL_OF_HARROGATH, false))
//                                        .set(new QuestStatus.Generic(Quest.RITE_OF_PASSAGE, false))
//                                        .set(new QuestStatus.Generic(Quest.EVE_OF_DESTRUCTION, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.HARROGATH, false))
//                                        .set(new WaypointStatus(Area.FRIGID_HIGHLANDS, false))
//                                        .set(new WaypointStatus(Area.ARREAT_PLATEAU, false))
//                                        .set(new WaypointStatus(Area.CRYSTALLINE_PASSAGE, false))
//                                        .set(new WaypointStatus(Area.HALLS_OF_PAIN, false))
//                                        .set(new WaypointStatus(Area.GLACIAL_TRAIL, false))
//                                        .set(new WaypointStatus(Area.FROZEN_TUNDRA, false))
//                                        .set(new WaypointStatus(Area.THE_ANCIENTS_WAY, false))
//                                        .set(new WaypointStatus(Area.WORLDSTONE_KEEP_LEVEL_2, false))
//                                        .done()
//                                        .build())
//                                .build()
//                )))
//                .build());
//    }
//
//    @Test
//    void testZeus() {
//        assertCharacter("/samples/Zeus.d2s", Character.builder()
//                .name("Zeus")
//                .level(2)
//                .clazz(CharacterClass.PALADIN)
//                .ladder(false)
//                .expansion(true)
//                .dead(false)
//                .hardcore(false)
//                .currentAct(Act.ACT1_NORMAL)
//                .activeEquipmentSet(EquipmentSet.MAIN)
//                .skillHotkeys(List.of())
//                .mouseSkill(new Swap<>(
//                        new Dual<>(Skill.fromName("Attack"), Skill.fromName("Attack")),
//                        new Dual<>(Skill.fromName("Attack"), Skill.fromName("Attack"))))
//                .progression(new DifficultyMap<>(Map.of(
//                        NORMAL, Character.Acts.builder()
//                                .act1(Act1Progression.builder()
//                                        .difficulty(NORMAL)
//                                        .visited(true)
//                                        .introduced(true)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.DEN_OF_EVIL, false))
//                                        .set(new QuestStatus.Generic(Quest.SISTERS_BURIAL_GROUNDS, false))
//                                        .set(new QuestStatus.Generic(Quest.TOOLS_OF_THE_TRADE, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_SEARCH_FOR_CAIN, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_FORGOTTEN_TOWER, false))
//                                        .set(new QuestStatus.Generic(Quest.SISTERS_TO_THE_SLAUGHTER, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.ROGUE_ENCAMPMENT, true))
//                                        .set(new WaypointStatus(Area.COLD_PLAINS, false))
//                                        .set(new WaypointStatus(Area.STONY_FIELD, false))
//                                        .set(new WaypointStatus(Area.DARK_WOOD, false))
//                                        .set(new WaypointStatus(Area.BLACK_MARSH, false))
//                                        .set(new WaypointStatus(Area.OUTER_CLOISTER, false))
//                                        .set(new WaypointStatus(Area.JAIL_LEVEL_1, false))
//                                        .set(new WaypointStatus(Area.INNER_CLOISTER, false))
//                                        .set(new WaypointStatus(Area.CATACOMBS_LEVEL_2, false))
//                                        .done()
//                                        .build())
//                                .act2(Act2Progression.builder()
//                                        .difficulty(NORMAL)
//                                        .visited(false)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.RADAMENTS_LAIR, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_HORADRIC_STAFF, false))
//                                        .set(new QuestStatus.Generic(Quest.TAINTED_SUN, false))
//                                        .set(new QuestStatus.Generic(Quest.ARCANE_SANCTUARY, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_SUMMONER, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_SEVEN_TOMBS, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.LUT_GHOLEIN, false))
//                                        .set(new WaypointStatus(Area.LUT_GHOLEIN_SEWERS_LEVEL_2, false))
//                                        .set(new WaypointStatus(Area.DRY_HILLS, false))
//                                        .set(new WaypointStatus(Area.HALLS_OF_THE_DEAD_LEVEL_2, false))
//                                        .set(new WaypointStatus(Area.FAR_OASIS, false))
//                                        .set(new WaypointStatus(Area.LOST_CITY, false))
//                                        .set(new WaypointStatus(Area.PALACE_CELLAR_LEVEL_1, false))
//                                        .set(new WaypointStatus(Area.ARCANE_SANCTUARY, false))
//                                        .set(new WaypointStatus(Area.CANYON_OF_THE_MAGI, false))
//                                        .done()
//                                        .build())
//                                .act3(Act3Progression.builder()
//                                        .difficulty(NORMAL)
//                                        .visited(false)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.LAM_ESENS_TOME, false))
//                                        .set(new QuestStatus.Generic(Quest.KHALIMS_WILL, false))
//                                        .set(new QuestStatus.Generic(Quest.BLADE_OF_THE_OLD_RELIGION, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_GOLDEN_BIRD, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_BLACKENED_TEMPLE, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_GUARDIAN, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.KURAST_DOCKS, false))
//                                        .set(new WaypointStatus(Area.SPIDER_FOREST, false))
//                                        .set(new WaypointStatus(Area.GREAT_MARSH, false))
//                                        .set(new WaypointStatus(Area.FLAYER_JUNGLE, false))
//                                        .set(new WaypointStatus(Area.LOWER_KURAST, false))
//                                        .set(new WaypointStatus(Area.KURAST_BAZAAR, false))
//                                        .set(new WaypointStatus(Area.UPPER_KURAST, false))
//                                        .set(new WaypointStatus(Area.TRAVINCAL, false))
//                                        .set(new WaypointStatus(Area.DURANCE_OF_HATE_LEVEL_2, false))
//                                        .done()
//                                        .build())
//                                .act4(Act4Progression.builder()
//                                        .difficulty(NORMAL)
//                                        .visited(false)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.THE_FALLEN_ANGEL, false))
//                                        .set(new QuestStatus.Generic(Quest.HELLS_FORGE, false))
//                                        .set(new QuestStatus.Generic(Quest.TERRORS_END, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.THE_PANDEMONIUM_FORTRESS, false))
//                                        .set(new WaypointStatus(Area.CITY_OF_THE_DAMNED, false))
//                                        .set(new WaypointStatus(Area.RIVER_OF_FLAME, false))
//                                        .done()
//                                        .build())
//                                .act5(Act5Progression.builder()
//                                        .difficulty(NORMAL)
//                                        .visited(false)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.SIEGE_ON_HARROGATH, false))
//                                        .set(new QuestStatus.Generic(Quest.RESCUE_ON_MOUNTAIN_ARREAT, false))
//                                        .set(QuestStatus.PrisonOfIce.builder()
//                                                .completed(false)
//                                                .scrollConsumed(false)
//                                                .build())
//                                        .set(new QuestStatus.Generic(Quest.BETRAYAL_OF_HARROGATH, false))
//                                        .set(new QuestStatus.Generic(Quest.RITE_OF_PASSAGE, false))
//                                        .set(new QuestStatus.Generic(Quest.EVE_OF_DESTRUCTION, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.HARROGATH, false))
//                                        .set(new WaypointStatus(Area.FRIGID_HIGHLANDS, false))
//                                        .set(new WaypointStatus(Area.ARREAT_PLATEAU, false))
//                                        .set(new WaypointStatus(Area.CRYSTALLINE_PASSAGE, false))
//                                        .set(new WaypointStatus(Area.HALLS_OF_PAIN, false))
//                                        .set(new WaypointStatus(Area.GLACIAL_TRAIL, false))
//                                        .set(new WaypointStatus(Area.FROZEN_TUNDRA, false))
//                                        .set(new WaypointStatus(Area.THE_ANCIENTS_WAY, false))
//                                        .set(new WaypointStatus(Area.WORLDSTONE_KEEP_LEVEL_2, false))
//                                        .done()
//                                        .build())
//                                .build(),
//                        NIGHTMARE, Character.Acts.builder()
//                                .act1(Act1Progression.builder()
//                                        .difficulty(NIGHTMARE)
//                                        .visited(true)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.DEN_OF_EVIL, false))
//                                        .set(new QuestStatus.Generic(Quest.SISTERS_BURIAL_GROUNDS, false))
//                                        .set(new QuestStatus.Generic(Quest.TOOLS_OF_THE_TRADE, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_SEARCH_FOR_CAIN, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_FORGOTTEN_TOWER, false))
//                                        .set(new QuestStatus.Generic(Quest.SISTERS_TO_THE_SLAUGHTER, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.ROGUE_ENCAMPMENT, true))
//                                        .set(new WaypointStatus(Area.COLD_PLAINS, false))
//                                        .set(new WaypointStatus(Area.STONY_FIELD, false))
//                                        .set(new WaypointStatus(Area.DARK_WOOD, false))
//                                        .set(new WaypointStatus(Area.BLACK_MARSH, false))
//                                        .set(new WaypointStatus(Area.OUTER_CLOISTER, false))
//                                        .set(new WaypointStatus(Area.JAIL_LEVEL_1, false))
//                                        .set(new WaypointStatus(Area.INNER_CLOISTER, false))
//                                        .set(new WaypointStatus(Area.CATACOMBS_LEVEL_2, false))
//                                        .done()
//                                        .build())
//                                .act2(Act2Progression.builder()
//                                        .difficulty(NIGHTMARE)
//                                        .visited(false)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.RADAMENTS_LAIR, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_HORADRIC_STAFF, false))
//                                        .set(new QuestStatus.Generic(Quest.TAINTED_SUN, false))
//                                        .set(new QuestStatus.Generic(Quest.ARCANE_SANCTUARY, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_SUMMONER, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_SEVEN_TOMBS, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.LUT_GHOLEIN, false))
//                                        .set(new WaypointStatus(Area.LUT_GHOLEIN_SEWERS_LEVEL_2, false))
//                                        .set(new WaypointStatus(Area.DRY_HILLS, false))
//                                        .set(new WaypointStatus(Area.HALLS_OF_THE_DEAD_LEVEL_2, false))
//                                        .set(new WaypointStatus(Area.FAR_OASIS, false))
//                                        .set(new WaypointStatus(Area.LOST_CITY, false))
//                                        .set(new WaypointStatus(Area.PALACE_CELLAR_LEVEL_1, false))
//                                        .set(new WaypointStatus(Area.ARCANE_SANCTUARY, false))
//                                        .set(new WaypointStatus(Area.CANYON_OF_THE_MAGI, false))
//                                        .done()
//                                        .build())
//                                .act3(Act3Progression.builder()
//                                        .difficulty(NIGHTMARE)
//                                        .visited(false)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.LAM_ESENS_TOME, false))
//                                        .set(new QuestStatus.Generic(Quest.KHALIMS_WILL, false))
//                                        .set(new QuestStatus.Generic(Quest.BLADE_OF_THE_OLD_RELIGION, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_GOLDEN_BIRD, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_BLACKENED_TEMPLE, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_GUARDIAN, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.KURAST_DOCKS, false))
//                                        .set(new WaypointStatus(Area.SPIDER_FOREST, false))
//                                        .set(new WaypointStatus(Area.GREAT_MARSH, false))
//                                        .set(new WaypointStatus(Area.FLAYER_JUNGLE, false))
//                                        .set(new WaypointStatus(Area.LOWER_KURAST, false))
//                                        .set(new WaypointStatus(Area.KURAST_BAZAAR, false))
//                                        .set(new WaypointStatus(Area.UPPER_KURAST, false))
//                                        .set(new WaypointStatus(Area.TRAVINCAL, false))
//                                        .set(new WaypointStatus(Area.DURANCE_OF_HATE_LEVEL_2, false))
//                                        .done()
//                                        .build())
//                                .act4(Act4Progression.builder()
//                                        .difficulty(NIGHTMARE)
//                                        .visited(false)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.THE_FALLEN_ANGEL, false))
//                                        .set(new QuestStatus.Generic(Quest.HELLS_FORGE, false))
//                                        .set(new QuestStatus.Generic(Quest.TERRORS_END, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.THE_PANDEMONIUM_FORTRESS, false))
//                                        .set(new WaypointStatus(Area.CITY_OF_THE_DAMNED, false))
//                                        .set(new WaypointStatus(Area.RIVER_OF_FLAME, false))
//                                        .done()
//                                        .build())
//                                .act5(Act5Progression.builder()
//                                        .difficulty(NIGHTMARE)
//                                        .visited(false)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.SIEGE_ON_HARROGATH, false))
//                                        .set(new QuestStatus.Generic(Quest.RESCUE_ON_MOUNTAIN_ARREAT, false))
//                                        .set(QuestStatus.PrisonOfIce.builder()
//                                                .completed(false)
//                                                .scrollConsumed(false)
//                                                .build())
//                                        .set(new QuestStatus.Generic(Quest.BETRAYAL_OF_HARROGATH, false))
//                                        .set(new QuestStatus.Generic(Quest.RITE_OF_PASSAGE, false))
//                                        .set(new QuestStatus.Generic(Quest.EVE_OF_DESTRUCTION, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.HARROGATH, false))
//                                        .set(new WaypointStatus(Area.FRIGID_HIGHLANDS, false))
//                                        .set(new WaypointStatus(Area.ARREAT_PLATEAU, false))
//                                        .set(new WaypointStatus(Area.CRYSTALLINE_PASSAGE, false))
//                                        .set(new WaypointStatus(Area.HALLS_OF_PAIN, false))
//                                        .set(new WaypointStatus(Area.GLACIAL_TRAIL, false))
//                                        .set(new WaypointStatus(Area.FROZEN_TUNDRA, false))
//                                        .set(new WaypointStatus(Area.THE_ANCIENTS_WAY, false))
//                                        .set(new WaypointStatus(Area.WORLDSTONE_KEEP_LEVEL_2, false))
//                                        .done()
//                                        .build())
//                                .build(),
//                        HELL, Character.Acts.builder()
//                                .act1(Act1Progression.builder()
//                                        .difficulty(HELL)
//                                        .visited(true)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.DEN_OF_EVIL, false))
//                                        .set(new QuestStatus.Generic(Quest.SISTERS_BURIAL_GROUNDS, false))
//                                        .set(new QuestStatus.Generic(Quest.TOOLS_OF_THE_TRADE, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_SEARCH_FOR_CAIN, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_FORGOTTEN_TOWER, false))
//                                        .set(new QuestStatus.Generic(Quest.SISTERS_TO_THE_SLAUGHTER, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.ROGUE_ENCAMPMENT, true))
//                                        .set(new WaypointStatus(Area.COLD_PLAINS, false))
//                                        .set(new WaypointStatus(Area.STONY_FIELD, false))
//                                        .set(new WaypointStatus(Area.DARK_WOOD, false))
//                                        .set(new WaypointStatus(Area.BLACK_MARSH, false))
//                                        .set(new WaypointStatus(Area.OUTER_CLOISTER, false))
//                                        .set(new WaypointStatus(Area.JAIL_LEVEL_1, false))
//                                        .set(new WaypointStatus(Area.INNER_CLOISTER, false))
//                                        .set(new WaypointStatus(Area.CATACOMBS_LEVEL_2, false))
//                                        .done()
//                                        .build())
//                                .act2(Act2Progression.builder()
//                                        .difficulty(HELL)
//                                        .visited(false)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.RADAMENTS_LAIR, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_HORADRIC_STAFF, false))
//                                        .set(new QuestStatus.Generic(Quest.TAINTED_SUN, false))
//                                        .set(new QuestStatus.Generic(Quest.ARCANE_SANCTUARY, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_SUMMONER, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_SEVEN_TOMBS, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.LUT_GHOLEIN, false))
//                                        .set(new WaypointStatus(Area.LUT_GHOLEIN_SEWERS_LEVEL_2, false))
//                                        .set(new WaypointStatus(Area.DRY_HILLS, false))
//                                        .set(new WaypointStatus(Area.HALLS_OF_THE_DEAD_LEVEL_2, false))
//                                        .set(new WaypointStatus(Area.FAR_OASIS, false))
//                                        .set(new WaypointStatus(Area.LOST_CITY, false))
//                                        .set(new WaypointStatus(Area.PALACE_CELLAR_LEVEL_1, false))
//                                        .set(new WaypointStatus(Area.ARCANE_SANCTUARY, false))
//                                        .set(new WaypointStatus(Area.CANYON_OF_THE_MAGI, false))
//                                        .done()
//                                        .build())
//                                .act3(Act3Progression.builder()
//                                        .difficulty(HELL)
//                                        .visited(false)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.LAM_ESENS_TOME, false))
//                                        .set(new QuestStatus.Generic(Quest.KHALIMS_WILL, false))
//                                        .set(new QuestStatus.Generic(Quest.BLADE_OF_THE_OLD_RELIGION, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_GOLDEN_BIRD, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_BLACKENED_TEMPLE, false))
//                                        .set(new QuestStatus.Generic(Quest.THE_GUARDIAN, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.KURAST_DOCKS, false))
//                                        .set(new WaypointStatus(Area.SPIDER_FOREST, false))
//                                        .set(new WaypointStatus(Area.GREAT_MARSH, false))
//                                        .set(new WaypointStatus(Area.FLAYER_JUNGLE, false))
//                                        .set(new WaypointStatus(Area.LOWER_KURAST, false))
//                                        .set(new WaypointStatus(Area.KURAST_BAZAAR, false))
//                                        .set(new WaypointStatus(Area.UPPER_KURAST, false))
//                                        .set(new WaypointStatus(Area.TRAVINCAL, false))
//                                        .set(new WaypointStatus(Area.DURANCE_OF_HATE_LEVEL_2, false))
//                                        .done()
//                                        .build())
//                                .act4(Act4Progression.builder()
//                                        .difficulty(HELL)
//                                        .visited(false)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.THE_FALLEN_ANGEL, false))
//                                        .set(new QuestStatus.Generic(Quest.HELLS_FORGE, false))
//                                        .set(new QuestStatus.Generic(Quest.TERRORS_END, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.THE_PANDEMONIUM_FORTRESS, false))
//                                        .set(new WaypointStatus(Area.CITY_OF_THE_DAMNED, false))
//                                        .set(new WaypointStatus(Area.RIVER_OF_FLAME, false))
//                                        .done()
//                                        .build())
//                                .act5(Act5Progression.builder()
//                                        .difficulty(HELL)
//                                        .visited(false)
//                                        .introduced(false)
//                                        .quests()
//                                        .set(new QuestStatus.Generic(Quest.SIEGE_ON_HARROGATH, false))
//                                        .set(new QuestStatus.Generic(Quest.RESCUE_ON_MOUNTAIN_ARREAT, false))
//                                        .set(QuestStatus.PrisonOfIce.builder()
//                                                .completed(false)
//                                                .scrollConsumed(false)
//                                                .build())
//                                        .set(new QuestStatus.Generic(Quest.BETRAYAL_OF_HARROGATH, false))
//                                        .set(new QuestStatus.Generic(Quest.RITE_OF_PASSAGE, false))
//                                        .set(new QuestStatus.Generic(Quest.EVE_OF_DESTRUCTION, false))
//                                        .done()
//                                        .waypoints()
//                                        .set(new WaypointStatus(Area.HARROGATH, false))
//                                        .set(new WaypointStatus(Area.FRIGID_HIGHLANDS, false))
//                                        .set(new WaypointStatus(Area.ARREAT_PLATEAU, false))
//                                        .set(new WaypointStatus(Area.CRYSTALLINE_PASSAGE, false))
//                                        .set(new WaypointStatus(Area.HALLS_OF_PAIN, false))
//                                        .set(new WaypointStatus(Area.GLACIAL_TRAIL, false))
//                                        .set(new WaypointStatus(Area.FROZEN_TUNDRA, false))
//                                        .set(new WaypointStatus(Area.THE_ANCIENTS_WAY, false))
//                                        .set(new WaypointStatus(Area.WORLDSTONE_KEEP_LEVEL_2, false))
//                                        .done()
//                                        .build())
//                                .build()
//                )))
//                .attribute(Attribute.STRENGTH, 25)
//                .attribute(Attribute.DEXTERITY, 20)
//                .attribute(Attribute.ENERGY, 15)
//                .attribute(Attribute.VITALITY, 25)
//                .attribute(Attribute.STAT_POINTS, 5)
//                .attribute(Attribute.SKILL_POINTS, 1)
//                .attribute(Attribute.LIFE, 57)
//                .attribute(Attribute.MAX_LIFE, 57)
//                .attribute(Attribute.MANA, 16)
//                .attribute(Attribute.MAX_MANA, 16)
//                .attribute(Attribute.STAMINA, 89)
//                .attribute(Attribute.MAX_STAMINA, 90)
//                .attribute(Attribute.EXPERIENCE, 1069)
//                .build());
//    }

    private static void assertCharacter(String file, Character character) {
        assertThat(PARSER.parse(requireNonNull(D2CloudStash.class.getResourceAsStream(file)))).isEqualTo(character);
    }
}

